### ISSUE TITLE
Geolocation: Widgetset 'com.vaadin.DefaultWidgetSet' does not contain an implementation for org.vaadin.addon.leaflet.LMap

### ISSUE THREAD

**Issue by GitMensch** [RapidClipse/rapidclipse-demo-mobilekit#1]
Steps to reproduce:

* import project -> from git
* preview
* choose geolocation

result:

    Widgetset 'com.vaadin.DefaultWidgetSet' does not contain an implementation for org.vaadin.addon.leaflet.LMap. Check the connector's @Connect mapping, the widgetset's GWT module description file and re-compile your widgetset.

**Comment by RapidClipse** [comment]
Hello GitMensch,

this is the default behaviour when you use our preview. As the Preview is designed to show _a single view_ it uses the _default widgetset,_ which does not contain additional widgets like the leaflet.

You can use the "Start Servlet"-button in our Quick Launch View to start the application with tomcat - then it loads the "rapidclipse_demo_mobilekitWidgetset", which _contains_ the addon widgets.

But be aware that you have to build and deploy _both,_ the war file and a android or iphone app file to access phone functionality with mobilekit!
